version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.7.1'
        PG_MAJOR: '12'
        NODE_MAJOR: '13'
        YARN_VERSION: '1.22.4'
        BUNDLER_VERSION: '2.1.4'
    image: ddd-store-dev:1.0.0
    tmpfs:
      - /tmp
    env_file:
      - .env

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - SMTP_HOST=mail
    depends_on:
      - postgres

  rails:
    <<: *backend
    command: ./bin/docker/start_rails
    ports:
      - '3000:3000'

  postgres:
    image: postgres:12.2
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  webpacker:
    <<: *app
    command: ./bin/docker/start_webpacker
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  mail:
    image: drujensen/mailcatcher:latest
    ports:
      - '1025:1025'
      - '1080:1080'

volumes:
  postgres:
  bundle:
  node_modules:
  rails_cache:
  packs: