default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i %>
  timeout: <%= ENV.fetch("PG_TIMEOUT_IN_SECONDS", 3).to_i.seconds %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  primary: &development_primary
    <<: *default
    host: <%= ENV.fetch("PG_HOST", "localhost") %>
    port: <%= ENV.fetch("PG_PORT", 5432).to_i %>
    database: <%= ENV.fetch("PG_DATABASE_NAME", "ddd_store_development") %>
  primary_replica:
    <<: *development_primary
    replica: true

test:
  primary: &test_primary
    <<: *default
    host: <%= ENV.fetch("PG_HOST", "localhost") %>
    port: <%= ENV.fetch("PG_PORT", 5432).to_i %>
    database: code_fund_ads_test
  primary_replica:
    <<: *test_primary
    replica: true
